# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-06 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='main_category',
            field=models.BooleanField(default=False),
        ),
    ]
