# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-14 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colour',
        ),
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.ManyToManyField(to='products.Colour'),
        ),
    ]
